name: psyscreen-test

services:
  auth-pg-test:
    image: postgres:17-alpine
    container_name: auth-pg-test
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - '${DATABASE_PORT:-5482}:5432'
    healthcheck:
      test:
        ['CMD-SHELL', 'pg_isready -U ${DATABASE_USER} -d ${DATABASE_NAME}']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    pull_policy: if_not_present