name: psyscreen

services:
  users-pg:
    image: postgres:17-alpine
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - '${DATABASE_PORT:-5482}:5432'
    healthcheck:
      test:
        ['CMD-SHELL', 'pg_isready -U $${{DATABASE_USER} -d $${{DATABASE_DB}']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
